
package ru.mts.tender.inline.foris.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ForisWS", targetNamespace = "http://synch.inline.tender.mts.ru/")
public interface ForisWS {


    /**
     * 
     * @param subscriberId
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetBalances")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetBalances", targetNamespace = "http://synch.inline.tender.mts.ru/", className = "ru.mts.tender.inline.foris.client.GetBalances")
    @ResponseWrapper(localName = "GetBalancesResponse", targetNamespace = "http://synch.inline.tender.mts.ru/", className = "ru.mts.tender.inline.foris.client.GetBalancesResponse")
    public String getBalances(
        @WebParam(name = "subscriberId", targetNamespace = "")
        String subscriberId);

}
