
package ru.mts.tender.inline.config.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "ESBConfigurationService", targetNamespace = "http://configuration.inline.tender.mts.ru/", wsdlLocation = "file:/K:/dvp/projects/nb_projects/Inline.task.2/Inline.task.2/src/main/resources/META-INF/wsdl/ESBConfigurationService.wsdl")
public class ESBConfigurationService
    extends Service
{

    private final static URL ESBCONFIGURATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException ESBCONFIGURATIONSERVICE_EXCEPTION;
    private final static QName ESBCONFIGURATIONSERVICE_QNAME = new QName("http://configuration.inline.tender.mts.ru/", "ESBConfigurationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/K:/dvp/projects/nb_projects/Inline.task.2/Inline.task.2/src/main/resources/META-INF/wsdl/ESBConfigurationService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESBCONFIGURATIONSERVICE_WSDL_LOCATION = url;
        ESBCONFIGURATIONSERVICE_EXCEPTION = e;
    }

    public ESBConfigurationService() {
        super(__getWsdlLocation(), ESBCONFIGURATIONSERVICE_QNAME);
    }

    public ESBConfigurationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns ESBConfigurationClientWS
     */
    @WebEndpoint(name = "ESBConfigurationClientWSPort")
    public ESBConfigurationClientWS getESBConfigurationClientWSPort() {
        return super.getPort(new QName("http://configuration.inline.tender.mts.ru/", "ESBConfigurationClientWSPort"), ESBConfigurationClientWS.class);
    }

    private static URL __getWsdlLocation() {
        if (ESBCONFIGURATIONSERVICE_EXCEPTION!= null) {
            throw ESBCONFIGURATIONSERVICE_EXCEPTION;
        }
        return ESBCONFIGURATIONSERVICE_WSDL_LOCATION;
    }

}
